name: builder

on:
  push:
    branches: ["main"]
    paths:
      - "**.go"
  pull_request:
    branches: ["main"]
    paths:
      - "**.go"
jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
      - name: Install dependencies
        run: go get ./cmd/auth-service
      - name: Build
        run: go build -v ./cmd/auth-service
