name: tester-coverage

on:
  push:
    branches: ["main"]
    paths:
      - "**.go"
  pull_request:
    branches: ["main"]
    paths:
      - "**.go"
jobs:
  lint:
    name: Test Coverage
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
      - name: Tests Permissions
        run: chmod +x ./.github/workflows/test.sh
      - name: Tests
        run: ./.github/workflows/test.sh
